version: "3.9"

services:

  docs:

      image: "squidfunk/mkdocs-material:latest"

      hostname: "ourchitecture"

      ports:
        - "8000:8000"

      volumes:
        - "./:/app"

      working_dir: "/app"
